
%
%common markers (TTLs) for turtle awake experiments
%urut/aug10
%

TTLs=[];

TTLs.STIMULUS_ON = 1;
TTLs.STIMULUS_OFF = 2;
TTLs.DELAY1_ON = 3;
TTLs.DELAY1_OFF = 4;
TTLs.DELAY2_ON = 5;
TTLs.DELAY2_OFF = 6;

TTLs.STIMULUS_ON_SEQUENCE_START = 20;
TTLs.STIMULUS_ON_SEQUENCE_END = 21;
TTLs.STIMULUS_ON_SEQUENCE_END_OMITTED = 22;


TTLs.STIMULUS_ON_SECONDARY = 10;
TTLs.STIMULUS_ON_SEQUENCE_FIRST = 15;
TTLs.STIMULUS_ON_SEQUENCE_SECOND_SKIPPED = 17;  %
TTLs.STIMULUS_ON_SEQUENCE_SECOND_SHOWN = 1;  %

TTLs.FIXCROSS_ON  = 100;
TTLs.FIXCROSS_OFF = 101;
TTLs.STIM_OFF     = 102;
TTLs.EXPERIMENT_ON = 55;
TTLs.EXPERIMENT_OFF = 66;
TTLs.EXPERIMENT_OFF_ERROR = 67;
TTLs.EXPERIMENT_OFF_ABORTED_MANUAL = 68;


